[package]
name = "semidata-web-parser"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rust-stdf = { version = "=1.1.0", default-features = false, features = ["serialize"] }
sha2 = "=0.10.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.128"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
panic = "abort"
